### ISSUE TITLE
subghz error - unsued parameter

### ISSUE THREAD

**Issue by dan3333** [jamisonderek/flipper-zero-tutorials#2] opened 2023-03-03 15:15 UTC
Hi, I am trying to compile the subghz demo myself as part of a custom fw but I am getting an error due to unused parameter.
is there anyway I can add a compilation flag to just treat it as warning instead of an error ? (I know it is slightly offtopic to the actual subghz and has more to do with flipper app compilation).
Thanks.

        CC      applications/plugins/subghz_demo/subghz_demo_app.c
applications/plugins/subghz_demo/subghz_demo_app.c: In function 'subghz_demo_play_tone':
applications/plugins/subghz_demo/subghz_demo_app.c:282:48: error: unused parameter 'demo_context' [-Werror=unused-parameter]
  282 | static void subghz_demo_play_tone(DemoContext* demo_context, DemoEvent* event) {
      |                                   ~~~~~~~~~~~~~^~~~~~~~~~~~
cc1: all warnings being treated as errors
scons: *** [build/f7-firmware-C/.extapps/Subghz_Demo/subghz_demo_app.o] Error 1
        SDKCHK  firmware/targets/f7/api_symbols.csv
API version 14.0 is up to date

**Comment by jamisonderek** [comment] 2023-03-04 15:23
Thanks for reporting the issue!  It looks like the latest toolchain requires that there are no unused variables or parameters (which wasn't a requirement when I was writing with the older toolset.)  I pushed a fix, so "git pull" should address the issues.  Sorry about that.

**Comment by jamisonderek** [comment] 2023-03-04 16:44
We would need to pass two additional parameters...  "-Wno-error=unused-variable -Wno-error=unused-parameter" to make those into warnings only.  Unfortunately, I'm not able to figure out if there is some kind of environment variable, py file, or json file we are supposed to change to pass the additional parameters to our gcc when we run FBT.


On Windows in official firmware I was able to run the following two commands:
```
scripts/toolchain/fbtenv.cmd

(fbt) C:\repo\flipper\firmware\official-firmware>arm-none-eabi-gcc -o build\\f7-firmware-D\\.extapps\\Subghz_Demo\\subghz_demo_app.o -c -std=gnu17 -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -Wall -Wextra -Werror -Wno-error=unused-variable -Wno-error=unused-parameter -Wno-address-of-packed-member -Wredundant-decls -Wdouble-promotion -fdata-sections -ffunction-sections -fsingle-precision-constant -fno-math-errno -g -Og -ggdb3 -mword-relocations -mlong-calls -fno-common -nostdlib -fvisibility=hidden -D_GNU_SOURCE -D\"M_MEMORY_FULL(x)=abort()\" -DSTM32WB -DSTM32WB55xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DHAVE_FREERTOS -DUSB_PMASIZE=0x400 -DLFS_CONFIG=lfs_config.h -DPB_ENABLE_MALLOC -DFURI_DEBUG -DNDEBUG -Ifuri -Iapplications\\services -Iapplications\\main -Ifirmware\\targets\\furi_hal_include -Ifirmware\\targets\\f7\\ble_glue -Ifirmware\\targets\\f7\\fatfs -Ifirmware\\targets\\f7\\furi_hal -Ifirmware\\targets\\f7\\inc -I. -Ilib -Ilib\\mlib -Ibuild\\f7-firmware-D\\assets\\compiled -Ilib\\STM32CubeWB\\Drivers\\CMSIS\\Device\\ST\\STM32WBxx\\Include -Ilib\\STM32CubeWB\\Drivers\\CMSIS\\Include -Ilib\\STM32CubeWB\\Drivers\\STM32WBxx_HAL_Driver\\Inc -Ilib\\STM32CubeWB\\Middlewares\\ST\\STM32_WPAN -Ilib\\drivers -Ilib\\FreeRTOS-Kernel\\include -Ilib\\FreeRTOS-Kernel\\portable\\GCC\\ARM_CM4F -Ilib\\FreeRTOS-glue -Ilib\\microtar\\src -Ilib\\toolbox -Ilib\\ST25RFAL002 -Ilib\\ST25RFAL002\\include -Ilib\\ST25RFAL002\\source\\st25r3916 -Ilib\\libusb_stm32\\inc -Ilib\\drivers -Ilib\\flipper_format -Ilib\\one_wire -Ilib\\infrared\\encoder_decoder -Ilib\\infrared\\worker -Ilib\\littlefs -Ilib\\mbedtls -Ilib\\mbedtls\\include -Ilib\\subghz -Ilib\\nfc -Ilib\\app-scened-template -Ilib\\callback-connector -Ilib\\digital_signal -Ilib\\fnv1a_hash -Ilib\\heatshrink -Ilib\\micro-ecc -Ilib\\nanopb -Ilib\\u8g2 -Ilib\\lfrfid -Ilib\\flipper_application -Ibuild\\f7-firmware-D\\.extapps\\Subghz_Demo applications\\plugins\\subghz_demo\\subghz_demo_app.c
```

**Comment by jamisonderek** [comment] 2023-03-04 18:09
I verified fix (using HackRF One get and give signals).  I Confirmed code is able to send/receive the count, low tone and high tone.

Pulled latest code from this repo.  Built and ran using official firmware from commit [5d4057f7](https://github.com/flipperdevices/flipperzero-firmware/commit/5d4057f7228b528896578ab6cf9d9a61b80a7c58).

**Closed by jamisonderek** 2023-03-04 18:09 UTC

**Comment by dan3333** [comment] 2023-03-04 23:42
That fixed it, thanks
